ARG CONFIG_PHP_COMPOSER_VERSION
FROM composer:${CONFIG_PHP_VERSION}

# Make config args persistent
ARG CONFIG_LOCAL
ARG CONFIG_DESTINATION
ENV CONFIG_LOCAL=${CONFIG_LOCAL}
ENV CONFIG_DESTINATION=${CONFIG_DESTINATION}

RUN addgroup -g 998 www && adduser -G www -g www -s /bin/sh -D www

WORKDIR $CONFIG_DESTINATION