# Static IP for VM. If you want IP auto assign use "0.0.0.0" and enable vagrant-auto_network plugin in Vagrant configs
ip: "10.10.0.20"
project_name: lemp-docker-vagrant-static-ip
hostname: lemp-docker-vagrant-static-ip.com
hostname_aliases:
  - name: ""

# Folder maps
local: ./
destination: /home/vagrant/lemp-docker-vagrant-static-ip # Do not end with /
type: nfs
create: true

# Default build commands
# You can use this to speed up your dev env and reduce any manual commands. It will run from destination directory after Vagrant is ready.
# Examples:
# $ docker-compose run composer install
# $ docker-compose run npm install
#
# Leave $ docker-compose up -d otherwise it will not provision the LEMP containers
build_commands:
  # Build custom images
  - docker-compose build

  # Boot container services
  - docker-compose up -d

  # Restart Docker daemon to reload network bridge and avoid issues
  - rc-service docker restart

  # Composer install
  # - docker-compose run composer install

  # NPM install
  # - docker-compose run npm install

# NGINX
nginx_version: "1.18.0"
nginx_docker_image: "alpine"

# PHP
php_version: "7.4"
php_docker_image: "fpm-alpine"
php_packages:
  - name: pdo
  - name: pdo_mysql
php_composer_version: "1"

# Node
node_version: "10"
node_docker_image: "alpine"

# MySQL
mysql_version: "5.7.29"
mysql_db: "mydatabase"
mysql_user: "myuser"
mysql_pass: "123"
mysql_root_pass: "root"

# Redis
redis_version: "5.0.6"
redis_docker_image: "alpine"
redis_port: 6379

# Vagrant configuration
vagrant_minimum_version: "2.1.0"
vagrant_box: generic/alpine312
vagrant_box_version: ""
vagrant_memory: 2048
vagrant_cpus: 2
vagrant_api_version: 2
vagrant_plugins:
  - name: vagrant-vbguest
  - name: vagrant-hostsupdater
  # Alternative for vagrant-hostsupdater
  # - name: vagrant-hostmanager

  # Useful to avoid IP conflict if not defining static IP
  # - name: vagrant-auto_network
vagrant_default_ports:
  - guest: 80
    host: 8000
  - guest: 443
    host: 44300
  - guest: 3306
    host: 33060
  - guest: 6379
    host: 63790
